version: "3.8"

services:
  # Optimisation Web Service
  web:
    build:
      context: web

    depends_on:
      - db

    environment:
      PYTHONPATH: /web

    ports:
      - 8005:8005

    networks:
      - db

    environment:
      PYTHONPATH: /web

    volumes:
      - ./web/:/web

    stdin_open: true
    tty: true

  db:
    image: postgres

    environment:
      POSTGRES_DB: web
      POSTGRES_USER: web
      POSTGRES_PASSWORD: topsecret

    ports:
      - 5432:5432

    networks:
      - db

  nginx:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

networks:
  db:
